# Uncomment the next line to define a global platform for your project
 platform :ios, '11.2'

target 'FirebaseChatApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseChatApp

  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  target 'FirebaseChatAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseChatAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
